.PHONY: debouncer_tb
debouncer_tb:
	xelab --prj prj/debouncer_tb.prj -debug all -O3 -rangecheck -stat \
		-v 0 xil_defaultlib.debouncer_tb

.PHONY: strobe_if_changed_tb
strobe_if_changed_tb:
	xelab --prj prj/strobe_if_changed_tb.prj -debug all -O3 -rangecheck -stat \
		-v 0 xil_defaultlib.strobe_if_changed_tb
